import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppProvider } from '@/contexts/AppContext'
import { BottomNavigation, TopNavigation } from '@/components/NavBar'
import FloatBtn from '@/components/FloatBtn'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Galileu Marcenaria',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <TopNavigation />
          <BottomNavigation />
          <FloatBtn />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  )
}
